[templates]
git_push_bookmark = '"rolf/push-" ++ change_id.short()'

[ui]
default-command = "log"
diff-editor = ":builtin"
diff-formatter = ":git"

[user]
name = "Rolf Erik Lekang"
email = "me@rolflekang.com"

[aliases]
push = ["util", "exec", "--", "uvx", "jj-pre-push==0.3.1", "push"]
