---
version: '3.1'

networks:
  dev:
    external: true

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: rolf
    networks:
      - dev
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
