#!/bin/bash

if [ ! -d Fira_Code ]; then
  wget https://github.com/tonsky/FiraCode/releases/download/4/Fira_Code_v4.zip
  unzip -o Fira_Code_v4.zip -d Fira_Code
  rm -rf Fira_Code*.zip
fi

if [ ! -d FiraCode ]; then
  wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
  unzip -o FiraCode.zip -d FiraCode
  rm -rf FiraCode/*Windows*
  rm -rf FiraCode*.zip
fi


if [[ "$(uname)" == 'Darwin' ]]; then
  cp -v FiraCode/*.ttf /Library/Fonts/
  cp -v Fira_Code/ttf/*.ttf /Library/Fonts/
else
  echo "Missing install for $(uname)"
  exit 1
fi
