#!/usr/bin/perl

use strict;
use warnings;

use LWP::UserAgent;

my $conf_dir = $ENV{'HOME'} . '/div/gcmnotify/';

open FILE_API_KEY, $conf_dir . 'api_key';
open FILE_DEVICES, $conf_dir . 'devices';
my $api_key = <FILE_API_KEY>;
my @devices = <FILE_DEVICES>;
close FILE_API_KEY;
close FILE_DEVICES;
chomp($api_key);
chomp(@devices);

my $action = $ARGV[0];
my $content;
if (not defined $action) {
    die 'You must specify an action';
} elsif ($action eq 'notify') {
    $content = '"data": { "action": "notify", "title": "' . $ARGV[1] . '", "body": "' . $ARGV[2] . '" }';
} elsif ($action eq 'cancel') {
    $content = '"data": { "action": "cancel" }';
} else {
    die 'Not a recognized action';
}

my $req = HTTP::Request->new(POST => 'https://android.googleapis.com/gcm/send');
$req->content_type('application/json');
$req->header('Authorization' => 'key=' . $api_key);
$req->content('{ "registration_ids": ["' . join('", "', @devices) . '"], ' . $content . ' }');

my $ua = LWP::UserAgent->new;
my $res = $ua->request($req);
print $res->as_string;
