#!/bin/sh

if test ! $(which brew)
then
  echo "  Installing Homebrew for you."
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)" > /tmp/homebrew-install.log
fi

brew tap phinze/cask
brew install grc coreutils brew-cask htop-osx wget unrar hub node mosh

exit 0
