#!/bin/sh

# Install Mac App Store Applications

mas install 413857545  # Divvy
mas install 443987910  # 1Password
mas install 1176895641 # Spark
mas install 409183694  # Keynote
mas install 803453959  # Slack
