#!/bin/bash

function extensions() {
  echo alexdima.copy-relative-path
  echo dbaeumer.vscode-eslint
  echo eamodio.gitlens
  echo EditorConfig.EditorConfig
  echo esbenp.prettier-vscode
  echo gaearon.subliminal
  echo GitHub.github-vscode-theme
  echo golang.go
  echo jaredly.reason-vscode
  echo ms-azuretools.vscode-docker
  echo ms-ossdata.vscode-postgresql
  echo editorconfig.editorconfig
  echo ms-python.python
  echo ms-python.vscode-pylance
  echo ms-toolsai.jupyter
  echo ms-vscode-remote.remote-containers
  echo ms-vscode-remote.remote-ssh
  echo ms-vscode-remote.remote-ssh-edit
  echo rofrol.monokai-ocean
  echo timonwong.shellcheck
  echo VisualStudioExptTeam.vscodeintellicode
  echo vscodevim.vim
  echo vscoss.vscode-ansible
  echo wmaurer.vscode-jumpy
  echo wolfmah.ansible-vault-inline
  echo hashicorp.terraform
}

for extension in $(extensions); do
  code --install-extension $extension
done
