set -g @catppuccin_flavour 'latte'
set -g message-style bg='#dce0e8',fg='#4c4f69'
set -g status-bg '#eff1f5'
set -g status-fg '#4c4f69'
setw -g window-status-style fg='#4c4f69',bg=default
setw -g window-status-current-style fg='#1e66f5',bg='#ccd0da'
set -g pane-active-border-style fg='#1e66f5'
set -g pane-border-style fg='#bcc0cc'
set -g mode-style 'fg=#4c4f69 bg=#ccd0da bold'
