onboarding = false

[keys]
workspace_picker = ""

[[keys.command]]
key = "prefix+w"
type = "popup"
command = "herdr-workspace-picker"
description = "jump to workspace"
width = "90%"
height = "80%"

[[keys.command]]
key = "prefix+j"
type = "popup"
command = "herdr-jjui-current-workspace"
description = "open jjui"
width = "90%"
height = "80%"

[[keys.command]]
key = "prefix+="
type = "shell"
command = "herdr-workspace-toggle"
description = "switch to last used workspace"

[[keys.command]]
key = "ctrl+h"
type = "plugin_action"
command = "vim-herdr-navigation.left"
description = "navigate left (vim/herdr)"

[[keys.command]]
key = "ctrl+j"
type = "plugin_action"
command = "vim-herdr-navigation.down"
description = "navigate down (vim/herdr)"

[[keys.command]]
key = "ctrl+k"
type = "plugin_action"
command = "vim-herdr-navigation.up"
description = "navigate up (vim/herdr)"

[[keys.command]]
key = "ctrl+l"
type = "plugin_action"
command = "vim-herdr-navigation.right"
description = "navigate right (vim/herdr)"

[ui]
pane_outer_borders = false
pane_gaps = false
